// Reference vocabulary for the Concept tab's "Similar To" and
// "Writer Style" attribute rows.
//
// - REFERENCE_ASPECTS: the short list of craft dimensions a user might
//   want to mirror from a film/show they list as a reference (e.g. "Give
//   me the pacing of Uncut Gems and the humor of Superbad").
// - WRITER_STYLES: a curated roster of well-known screen and TV writers
//   the user can tag as style anchors. These are display strings; we
//   persist them verbatim since the list itself is the identifier space.

export const REFERENCE_ASPECTS: string[] = [
  "writing style",
  "dialogue",
  "pacing",
  "structure",
  "humor",
  "tone",
  "atmosphere",
  "cinematography",
  "visual style",
  "editing",
  "score",
  "sound design",
  "world-building",
  "character development",
  "ensemble dynamics",
  "themes",
  "emotional register",
  "plot mechanics",
  "genre blend",
  "subtext",
  "voiceover",
  "production design",
  "costume",
  "twist craft",
];

// ~60 contemporary + canonical screen/TV writers. Display-only labels —
// what the user sees is what we store on settings.writerStyles.
export const WRITER_STYLES: string[] = [
  "Aaron Sorkin",
  "Armando Iannucci",
  "Ava DuVernay",
  "Barry Jenkins",
  "Beau Willimon",
  "Billy Wilder",
  "Bo Burnham",
  "Bong Joon-ho",
  "Cameron Crowe",
  "Charlie Brooker",
  "Charlie Kaufman",
  "Christopher Nolan",
  "Coen Brothers",
  "Craig Mazin",
  "Damon Lindelof",
  "Dan Harmon",
  "David Lynch",
  "David Mamet",
  "David Simon",
  "Diablo Cody",
  "Donald Glover",
  "Emerald Fennell",
  "Greta Gerwig",
  "Hayao Miyazaki",
  "Issa Rae",
  "Jane Campion",
  "Jesse Armstrong",
  "John Hughes",
  "Jordan Peele",
  "Judd Apatow",
  "Larry David",
  "Lin-Manuel Miranda",
  "Martin McDonagh",
  "Matthew Weiner",
  "Michaela Coel",
  "Mike Schur",
  "Mike White",
  "Nancy Meyers",
  "Noah Baumbach",
  "Nora Ephron",
  "Paul Thomas Anderson",
  "Phoebe Waller-Bridge",
  "Quentin Tarantino",
  "Rebecca Sugar",
  "Rian Johnson",
  "Richard Linklater",
  "Robert Towne",
  "Ryan Murphy",
  "Sam Esmail",
  "Shonda Rhimes",
  "Sofia Coppola",
  "Spike Lee",
  "Steven Moffat",
  "Taylor Sheridan",
  "Tina Fey",
  "Tony Gilroy",
  "Vince Gilligan",
  "Wes Anderson",
  "William Goldman",
];
